# Generated by Django 4.1.1 on 2022-10-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_educativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
