# Generated by Django 4.1.1 on 2022-10-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_educativo', '0002_rename_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='centro_educativo.courses'),
        ),
    ]
