# Generated by Django 4.1.1 on 2022-10-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_educativo', '0004_students_courses_alter_students_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students_Courses',
            new_name='StudentsCourses',
        ),
    ]
