# Generated by Django 4.1.1 on 2022-11-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_educativo', '0006_rename_course_id_studentscourses_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.DeleteModel(
            name='StudentsCourses',
        ),
    ]
